name: Add new pr or issue to project board 

on: [issues, pull_request]    

jobs:
  add-to-project:
    name: Add issue or pr to project
    uses: lambdaisland/open-source/.github/workflows/add-to-project-board.yml@LIOSS-1/add-pr-and-issue-to-project-board
